[MISC] Support python 3.8, 3.9, 3.10
CGnal/cgnal-core pull request #19
Opened 2022-03-22 18:15 UTC by NicolaDonelli

Closes issue #1, also adding compatibility checks with python 3.8 and 3.9

2022-03-24 22:16 UTC, deusebio requested changes
Just a couple of comments. 

I only have an issue with the commit message. The commit is 2% about providing support to python 3.8, 3.9 and 3.10 (you only udated requirements and CI pipeline, right?) and the majority of modifications are about documentation. 

If possible, I belive it would be better to separate the two things in two different commits

2022-03-24 22:16 UTC, deusebio commented on Makefile
> +#clean: uninstall clean_cache
can we remove this?

2022-03-24 22:16 UTC, deusebio commented on Makefile
You forgot to add the "--no-deps" to pip

2022-03-25 08:43 UTC, NicolaDonelli commented
Yup, you are right. I splitted the commit in two added the `--no-deps` flag to pip install tar and removed the commented lines.

2022-04-01 10:08 UTC, deusebio approved these changes

2022-04-01 13:35 UTC, merged