[ISSUE-22] Fix private variable naming scheme
CGnal/cgnal-core pull request #31
Opened 2022-04-20 14:11 UTC by aiola

2022-04-20 14:20 UTC, NicolaDonelli requested changes
Everything seems functionally fine, but why did you choose to use two different nomenclatures (one with a double leading underscore, the other one with a single leading underscore)?
I would prefer to keep the same nomenclature everywhere (no matter which one...)

2022-04-20 14:20 UTC, NicolaDonelli commented on cgnal/core/data/layer/__init__.py
> +        def __iterator():
Why using two leading underscores here while using a single underscore in most other cases?

2022-04-20 14:20 UTC, NicolaDonelli commented on cgnal/core/data/layer/mongo/archivers.py
> +    def __insert(self, obj: T) -> UpdateResult:
Same as above

2022-04-20 14:20 UTC, NicolaDonelli commented on cgnal/core/data/model/ml.py
> +    def __check_features(features: List[np.ndarray]) -> None:
Same as above

2022-04-20 14:20 UTC, NicolaDonelli commented on cgnal/core/utils/decorators.py
> +    def __cache(self):
Same here

2022-04-20 17:32 UTC, NicolaDonelli commented
Ok, got it. 
But, since in python nothing is truly private, we never put too much attention name mangling. 
Having said that, I am not against adopting this differentiation but since, in principle, we never wanted to do name mangling (except for magic methods, we always wanted to simply point out that a given method should not be directly accessed by the user), I would be cautious in differentiating between these two types of hidden methods.

2022-04-22 12:48 UTC, aiola commented
> Ok, got it. But, since in python nothing is truly private, we never put too much attention name mangling. Having said that, I am not against adopting this differentiation but since, in principle, we never wanted to do name mangling (except for magic methods, we always wanted to simply point out that a given method should not be directly accessed by the user), I would be cautious in differentiating between these two types of hidden methods.

Ok, I fixed it. All private methods have now a single leading underscore.

2022-04-26 09:41 UTC, NicolaDonelli approved these changes
Fine by me

2022-04-26 09:42 UTC, merged