[MISC] Adding type T specification for BaseIterable and enhance funct…
CGnal/cgnal-core pull request #38
Opened 2022-05-16 15:43 UTC by deusebio

…ionalities with empty method

2022-06-07 10:40 UTC, NicolaDonelli requested changes

2022-06-07 10:40 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +    def __lazyType__(self) -> Type[L]:
Didn't we decide not to use the double-underscore syntax for hidden methods (since flake8 suggests that it should be used only for magic methods)? @aiola also did a refactoring PR to remove all the usages from the package...

2022-06-07 10:40 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +        return LazyIterable[T]
Does this new Generic form still work fine with `issubclass`? I do not think it is possible (yet) to check the complete Generic expression (i.e. that a class is a LazyIterable of specific objects) but will this still return `true` if we run `issbuclass(self.__lazyType__, LazyIterable)`?

2022-06-07 10:40 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +
This implementation could return different values when `__type__ = None` and `self.items` contains objects of different types. Are we fine with this eventuality?

2022-06-14 15:39 UTC, deusebio commented on cgnal/core/data/model/core.py
> +        self._type = self.type
It was done in order to raise Errors / infer the type straight away in the constructor. However, I kinda like @aiola proposal, so i'll refactor this accordingly

2022-06-14 15:39 UTC, deusebio commented on cgnal/core/data/model/core.py
> +    def __lazyType__(self) -> Type[L]:
yes, sure

2022-06-14 15:40 UTC, deusebio commented on cgnal/core/data/model/core.py
> +        return LazyIterable[T]
not sure it would. But why do we need this to be working? The lazyType is used in order to have the type to cast objects, not to perform a issubclass function call

2022-06-14 15:42 UTC, deusebio commented on cgnal/core/data/model/core.py
> +
yes, sure. I kinda like the overall idea.

2022-06-14 20:32 UTC, deusebio commented on cgnal/core/data/model/core.py
> +    def __lazyType__(self) -> Type[L]:
Uhm, actually this is not handled properly by Python. I'm actually afraid that we cannot define abstract methods with the double underscore. Try to run this minimal example (and then change methods to magic methods...)

```
from abc import ABC, abstractmethod

class AbstractTest(ABC):
    
    @property
    @abstractmethod
    def __test(self): ...
        
        
class Test(AbstractTest):
    
    def __test(self):
        return 1
    
a = Test()
```

2022-06-14 20:37 UTC, deusebio commented
Ok I have taken a look at the comments and came up with a new implementation, which incorporates @aiola suggestion, although in a slightly different fashion. 

The idea is that `type` is actually abstract in the _BaseIterable. In fact, Documents and Datasets (which extends from _BaseIterable) do not need this specification, as we know that objects should be Document and Sample, respectively. On the other hand, the more generic implementation BaseIterable (to be used in generic cases where the Iterable is not typed), the @aiola inferring strategy is used. 

I'm starting to like this new implementation but I'm eager to hear on what you think

2022-07-01 12:30 UTC, aiola approved these changes
Good to go!

2022-07-04 07:59 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +    def __lazyType__(self) -> Type[L]:
I agree: we actually decided **NOT** to use it. We adopted the single underscore syntax.

2022-07-04 08:00 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +        return LazyIterable[T]
I agree, I was just curious about a possible side usage.

2022-07-04 08:04 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +        return cls([])
Didn't `flake` complain about this method without docstrings?
In case it doesn't, I do. ;)

2022-07-04 08:06 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +        ...
I think this is an unwanted change, reverting the more complete previous implementation...

2022-07-04 08:06 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +        ...
Same as above

2022-07-04 08:10 UTC, NicolaDonelli commented on cgnal/core/data/model/core.py
> +        super().__init__(items)
In cases like this one where we have more than one ancestor, I find this syntax to call the ancestor's method a bit unclear. 
Wouldn't it be easier to read calling `Ancestor.__init__(self, items)`? This way it would be obvious which __init__ we are calling...

2022-07-06 21:08 UTC, merged