[ISSUE-40] Create sample datasets
CGnal/cgnal-core pull request #42
Opened 2022-06-15 16:37 UTC by deusebio

2022-07-04 07:20 UTC, deusebio commented on cgnal/core/datasets/__init__.py
> +weather_nyc = _create_nyc_dataset(os.path.join(DATA_FOLDER, "weather_nyc_short.csv"))
I don't mind. The only drawback I'm thinking of is that we can't import the data straight away, like 

`from cgnal.core.datasets import weather_nyc`

but it always requires to call the function, but it is not a major point, and I'm fine with swapping to a function

Let's see what also @nromeoarena says

2022-07-04 09:57 UTC, nromeoarena commented on cgnal/core/datasets/__init__.py
> +weather_nyc = _create_nyc_dataset(os.path.join(DATA_FOLDER, "weather_nyc_short.csv"))
I agree with the @aiola suggestion, better to implement a function call, than defining a global variable.

2022-07-04 09:58 UTC, nromeoarena requested changes
apart the comment on the global variable, all seems ok

2022-07-07 07:31 UTC, aiola approved these changes

2022-07-07 07:40 UTC, nromeoarena approved these changes
ok

2022-07-07 08:00 UTC, merged